import "./globals.scss";
import BackgroundImage from "@/components/backgroundImage/backgroundImage";
import Header from "@/components/navigation/Header";
import Footer from "@/components/navigation/Footer";
import StoreProvider from "../lib/store/StoreProvider";
import { SessionProvider } from "next-auth/react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Mythras NextJS project",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
        <StoreProvider>

          <BackgroundImage />

          <Header />
          {children}
          <Footer />
          
        </StoreProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
